### ISSUE TITLE
Is it font dependent ? 

### ISSUE THREAD

**Issue by d0ob** [vscode-plugins/alignText#4]
Hi there ! 

First, thanks ! Straightforward, efficient, instant, it works very well ! 
And I had to test multiple extensions before finding one that always gives me the expected results...

There is one thing though, I have the same problem as for some other extension I use : 
It seems dependent on the font, and so, it's not aligned properly unless using the default one. 
Can I do something about that ? Or am I doomed to choose between font and features ? =(

PS: Since I'm here ^^ I wonder something else, but it's very nitpicking this time :
Could it be possible to make the default symbol, the "=" in the selection when opening the command, customizable ?

**Comment by Esteban-Rocha** [comment]
@d0ob Maybe you can try with all the other extensions disabled to check if this is not a bug from another one?? I use `Victor` Mono and `Jet-brains Mono` and it works good with both 🤔

**Comment by d0ob** [comment]
Thanks for your quick answer =)

Yes there are a few fonts that don't hurt the alignment, but a lot do, like all the fancy ones for example :
JetBrains Mono, Segoe Print, Comic sans ms, Ink Free, Symbol... ( Yes, I could totally use Symbol otherwise, obviously ! ^^)

I suppose that's why only a select few are suggested as valid fonts.
Not sure what causes it though, but I guess they're just calibrated differently and that's it...
Or maybe it is a weird interaction with something else indeed, I didn't even mention that I'm on Windows, if it changes anything.
I came back to Consolas, I miss the fun and the spacing, but that's a price I'm willing to pay to not ruin multiple features I like ^^

**Comment by serge1** [comment]
Hi @d0ob , might it be that you are trying to align text when using proportional fonts? The plugin does aligning by inserting space characters. When working with non-monospace fonts, insertion of spaces may not align visually.

**Comment by d0ob** [comment]
Hi serge1 =)

Yes it sure sound like spacing related !

Though, being very new to VScode (and very noob to code in general) I'm not sure about what I do, or what I don't do, that creates it... What I can say is how I do it : By adding the default setting's string in the json and replacing the font's name, like so, for example : 

[...]
"editor.fontFamily": "Consolas, 'Courier New', monospace",

becomes
[...]
"editor.fontFamily": "Segoe Print, 'Courier New', monospace",


Can it be done differently to not screw the spacing, and thus, using any font without handicap related plugins ?!

**Comment by serge1** [comment]
'Segoe Print' is a proportional font. Meaning - each character has a different width. So, while the same letters are on the same position from the beginning of line, depending on other characters that come before, the letters may be visually located at different columns. To have a better aligning, use monospace font (the font that draws each character with the same width)

**Comment by d0ob** [comment]
Ooooh yes I see, I see ! I was totally oblivious to the terminology, and "font making" in general, in fact. Makes clear sens now !
It is only now that I understand the "I suggest using monospace font" that I indeed had already read when searching about how to customize the font ! But that I had stupidly misinterpreted as "be sure to keep the "monospace" at the end of the setting" xD And it's also only now, reading more about it, that I understand the setting string itself ^^ 

Thanks for your answer and pedagogy ! =)
